### ISSUE TITLE
As a Service

### ISSUE THREAD

**Issue by hoseinit** [SilenceDut/TaskScheduler#1]
How can this library be used as a background service doing a repeated task?

**Comment by SilenceDut** [comment]
you had better doing such thing in a Service using this library, because a thread priority is low ,may be recycle

**Comment by hoseinit** [comment]
I am wondering what is the difference between:
1. Using a service with AlarmManager setting next wakeup
2. Using a service with your Taskscheduler

**Comment by SilenceDut** [comment]
service with a AlarmManager is using for alarm for a time,Taskscheduler is using for doing async task ,I think they don't have relation。service is a environment ，Taskscheduler  is just a thread tool ,Taskscheduler can be used in service,Taskscheduler not care where it was be used

**Comment by hoseinit** [comment]
I am using AlarmManager to Wake the Service Up in a periodic manner.
I sent some data to the server when the service wakes up.
So I am wondering what benefit has your Great library in comparison to my approach
