### ISSUE TITLE
支持延时任务

### ISSUE THREAD

**Issue by Eklett** [SilenceDut/TaskScheduler#2]
不支持像Executor.schedule(runnable, delay, timeUnit)的延时任务？

**Comment by SilenceDut** [comment]
runOnUIThread(Runnable runnable,long delayed)？

**Comment by SilenceDut** [comment]
runOnUIThread(Runnable runnable,long delayed)？或者拿到异步hander进行延时？

**Comment by Eklett** [comment]
这个runOnUIThread是在UI线程执行的？想要background线程的

**Comment by SilenceDut** [comment]
provideHandler(String backgroundName).runDelay()

**Comment by Eklett** [comment]
provideHandler在1.0.1是private的方法, readme还是1.0.1，jitpack已经1.0.3了
