### ISSUE TITLE
咨询~

### ISSUE THREAD

**Issue by qzqs** [SilenceDut/TaskScheduler#4]
TaskScheduler.execute(new Task<String>() {
                    @Override
                    public boolean doInBackground() throws InterruptedException {

                                           }
                    @Override
                    public void onSuccess(boolean result) {
                        /**UI线程*/
                                       }
                });
为什么这样写TaskScheduler.execute(new Task<String>() {}
中的new Task<String>() 就会报错。
而 Task task = new Task<String>() {}
就不会报错呢？

**Comment by ylmyg** [comment]
...发现错误了，好像是不支持返回boolen的，只支持返回String的么？

**Comment by SilenceDut** [comment]
TaskScheduler.execute(new Task<Boolean>() {
            @Override
            public Boolean doInBackground() {
                return null;
            }

            @Override
            public void onSuccess(Boolean result) {
                
            }

        });

**Comment by SilenceDut** [comment]
TaskScheduler.execute(new Task< Boolean >() {
            @Override
            public Boolean doInBackground() {
                return null;
            }

            @Override
            public void onSuccess(Boolean result) {
                
            }

        });

**Comment by qzqs** [comment]
原来是这样，明白了~
