### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by OrangeHao** [SilenceDut/TaskScheduler#5]
我在一个图片列表里不断的TaskScheduler.execute(new Task())执行一个下载图片的任务
然后就crach了，是我使用姿势不对么
version：2.4.0

**Comment by SilenceDut** [comment]
应该是你同时下载图片太多了，任务过多导致任务被拒绝，这是线程池的限制，可以崩溃是故意没有隐藏的，不然其他线程也都会被这些任务完全占有。建议用一个异步的handler去做下载或者用TaskScheduler.ioHandler().post

**Comment by SilenceDut** [comment]
或者TaskScheduler.provideHandler(String handlerName).post()
