### ISSUE TITLE
removeHandlerCallback这个方法没找到？

### ISSUE THREAD

**Issue by ysy950803** [SilenceDut/TaskScheduler#7]
请问下是弃用了吗还是开发中？

**Comment by SilenceDut** [comment]
removeHandlerCallback这个接口不需要了，忘了更新文档了，直接拿到自己创建的异步的handler remove就好了

**Comment by ysy950803** [comment]
OK!

**Comment by ysy950803** [comment]
@SilenceDut 哈喽，顺便再问一下，目前是不是没有一个类似cancelAllTasks的方法来结束所有任务？

**Comment by SilenceDut** [comment]
是的，那样设计不太好
